### ISSUE TITLE
Retaining creation/modification dates

### ISSUE THREAD

**Issue by jhaungs** [yifaneye/macos-notes-exporter#1]
I wrote almost this same script before I found yours. One thing lacking in both versions is the retention of the creation and modification dates for each note. 

There are methods on the Note object for these dates:

var cdate = note.creationDate
var mdate = note.modificationDate

And what I'd like to do is something like below, to transfer these dates to the exported note files.

var app = Application.currentApplication();
var file = app.openForAccess(Path(filename), { writePermission: true });
app.setEof(file, { to: 0 });
app,setCreateDate(file, { to: note.creationDate});           
app,setModifiedDate(file, { to: note.modificationDate});

But I can't find how to (a) format the date objects in this version of Javascript, or (b) find methods to assign the dates to the generated file. 

Any ideas, either how to do this, or where to find the right APIs?

**Comment by jhaungs** [comment]
If you try to run this, you'll get an error "Can't convert types."

Believe it or not, you can't even this.console.log(cdate); same error.

**Comment by jhaungs** [comment]
All I really wanted was the dates for each note. Turns out this is easy in AppleScript:

```
tell application "Notes"
	repeat with theNote in notes
		set theFolder to container of theNote
		set folderName to name of theFolder
		set noteName to name of theNote
		set cdate to creation date of theNote
		set mdate to modification date of theNote
		log folderName & tab & noteName & tab & cdate & tab & mdate
	end repeat
end tell
```

**Comment by yifaneye** [comment]
Hi @jhaungs, I will look into it and get back to you. For the APIs, I don't think one can set creation and modification date using JavaScript.
